# Generated by Django 3.1.2 on 2020-10-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Телефон', 'Телефон'), ('Компьютер', 'Компьютер'), ('Видеокарта', 'Видеокарта'), ('Жесткий диск', 'Жесткий диск')], max_length=50, null=True),
        ),
    ]
