# Generated by Django 3.1.2 on 2020-11-03 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_customer_image_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='image_field',
            new_name='image',
        ),
    ]
