# Generated by Django 3.1.2 on 2020-11-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20201104_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, default='default_image.jpeg', null=True, upload_to=''),
        ),
    ]
